### ISSUE TITLE
Telegram-Integration verbessern

### ISSUE THREAD

**Issue by Salocinf** [TimoScheuermann/FitnessHub#10]
- Was muss hier gemacht werden?
- Wie soll Telegram integriert werden?
- Telegram-Bot?

**Comment by TimoScheuermann** [comment]
Ab jetzt wieder möglich TG zu verbinden. Features noch offen

**Comment by TimoScheuermann** [comment]
Telegram kann genutzt werden um offline Nachrichten von Freunden zu erhalten.
Es gibt einen Telegram Channel der die Posts aus dem Feed mit "dokumentiert" https://t.me/FHUpdates
