### ISSUE TITLE
Konzept für Feed

### ISSUE THREAD

**Issue by JeannineB** [TimoScheuermann/FitnessHub#23]
- was anzeigen (wenn neue Übung hinzugefügt wurde)
- was teilen
- welche Inhalte

**Comment by Salocinf** [comment]
# Nutzer

- Rezepte teilen
- Workout teilen
- Übung teilen
- Erfolge/Challenges teilen
- Evtl. Verfassung/Stimmung teilen

# FitnessHub

- Zuletzt hinzugefügte Rezepte
- Zuletzt hinzugefügte Übungen
- Zuletzt hinzugefügte Ernährungspläne
- Beiträge (Motivation, Werbung, generelle News, Events in Umgebung)

# Sonstige Funktionen

- Reaktionen: Auswahlmöglichkeiten (
![image](https://user-images.githubusercontent.com/42444892/110125512-ada07180-7dc3-11eb-88ef-e92a54b95f99.png))
