### ISSUE TITLE
"Schritt hinzufügen" - Weitere Hinweise does not work

### ISSUE THREAD

**Issue by JeannineB** [TimoScheuermann/FitnessHub#26]
![image](https://user-images.githubusercontent.com/43883074/109399463-3db56580-7943-11eb-8493-6a3c89a4b47c.png)

**Comment by TimoScheuermann** [comment]
Fehler lag hieran: https://github.com/TimoScheuermann/FitnessHub/blob/master/frontend-redesign/src/components/forms/FHExerciseForm.vue#L173

**Comment by TimoScheuermann** [comment]
Resolved: https://github.com/TimoScheuermann/FitnessHub/commit/efca8c45267b84a5bf87cb398df00d4ea3defa5c
