### ISSUE TITLE
Possible duplicate

### ISSUE THREAD

**Issue by TimoScheuermann** [TimoScheuermann/FitnessHub#33]
Ist das gewollt?
![image](https://user-images.githubusercontent.com/48986503/110024924-0540cd80-7d2f-11eb-8f05-f061e12e58ca.png)

**Comment by JeannineB** [comment]
Lol die hab ich glaube ich nicht erstellt... ich schaue mal nach :D

**Comment by JeannineB** [comment]
Lösch bitte die mit deinem Bild
