### ISSUE TITLE
update landing screenshots

### ISSUE THREAD

**Issue by TimoScheuermann** [TimoScheuermann/FitnessHub#41]

**Comment by JeannineB** [comment]
@JeannineB in Doku ergänzen

**Comment by TimoScheuermann** [comment]
@Salocinf Bitte prüfen, ob wirklich für jede Kachel ein Bild existiert

**Comment by TimoScheuermann** [comment]
@Salocinf beim Feed wirklich nur ein einzelnes Bild nicht mehrere nebeneinander?

**Comment by Salocinf** [comment]
See 5ccf4c250bb100179bbe142e815777a5e2b35dc5 for updated landing screenshots and cards. @TimoScheuermann please upload pictures onto AWS and change respective paths in code.

**Comment by TimoScheuermann** [comment]
done.
